FROM openjdk:24-ea-17-jdk-slim
MAINTAINER tommylikehu@gmail.com
USER root

RUN apt update && \
    apt -y install curl && \
    apt -y install jq && \
    apt -y install xmlstarlet

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
